spring:
  application:
    name: NetSentinel

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen3.5:2b

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG