net-sentinel:
  mcp:
    allowed-tools: search, fetch_content
  agent:
    auto-approve: false
    planner:
      prompt: "
              Ты — SRE Planner. Разбей проблему на атомарные шаги диагностики.
              Используй только доступные инструменты.
              Твой ответ должен быть СТРОГО в формате JSON:
              "
    executor:
      prompt: "Выполни конкретную задачу диагностики. Используй инструменты."
    answerer:
      prompt: "
              Ты — ведущий SRE-инженер. Твоя задача: проанализировать результаты диагностики и дать осознанный ответ.
              Если проблема решена — объясни причину. 
              Если данных недостаточно — честно скажи, чего не хватает, и предложи варианты.
              Будь краток и техничен.
              "
    user:
      prompt: "
              Ты — Senior SRE инженер NetSentinel.
              Работай по логике:
              1. Thought: Опиши кратко, что ты собираешься сделать.
              2. Выполни действие (используй инструменты).
              3. Final Answer: Дай итоговый ответ на основе полученных данных.
              "
    kuma:
      prompt: "
              KUMA prompt
              "


server:
  port: 8080

spring:
  application:
    name: NetSentinel

  ai:
    ollama:
      base-url: ${OLLAMA_URL:http://localhost:11434}
      chat:
        options:
          model: qwen3.5:4b
    mcp:
      client:
        enabled: true
        streamable-http:
          connections:
            docker-gateway:
              url: ${DOCKER_GATEWAY_URL:http://localhost:8811}
        headers:
          # docker mcp gateway run --profile dev_tools --port 8811 --transport streaming
          Authorization: ${GATEWAY_AUTHORIZATION_TOKEN:Bearer lhyestnafrqir0u1sbffelxjvtteed550hej7vlu2i9mfslpcn}

logging:
  level:
#    root: DEBUG
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG
          ollama: DEBUG
          model:
            function: DEBUG
    com:
      project:
        netsentinel:
          core:
            config:
              chatClients: DEBUG
